// One code per rule. The subject forbids a single generic error, so every
// refusal in the app comes from this list.
export const ViolationCode = {
  ROLE_NOT_PERMITTED_AT_LEVEL: 'ROLE_NOT_PERMITTED_AT_LEVEL',
  OUT_OF_SCOPE_QUARTER: 'OUT_OF_SCOPE_QUARTER',
  QC_WITHOUT_QUARTER: 'QC_WITHOUT_QUARTER',

  NO_RESERVATION_AT_LEVEL_1: 'NO_RESERVATION_AT_LEVEL_1',
  INTER_QUARTER_TRANSFER_FORBIDDEN: 'INTER_QUARTER_TRANSFER_FORBIDDEN',
  TRANSIT_FORBIDDEN_AT_LEVEL: 'TRANSIT_FORBIDDEN_AT_LEVEL',

  SAME_SOURCE_AND_DESTINATION: 'SAME_SOURCE_AND_DESTINATION',
  NOT_ADJACENT: 'NOT_ADJACENT',
  NO_ROUTE_AVAILABLE: 'NO_ROUTE_AVAILABLE',
  MARITIME_ROUTE_UNAVAILABLE: 'MARITIME_ROUTE_UNAVAILABLE',
  TRANSIT_APPROVAL_REQUIRED: 'TRANSIT_APPROVAL_REQUIRED',
  TRANSIT_APPROVAL_DENIED: 'TRANSIT_APPROVAL_DENIED',

  ADJACENT_SOURCE_AVAILABLE: 'ADJACENT_SOURCE_AVAILABLE',

  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  RETENTION_THRESHOLD_BREACH: 'RETENTION_THRESHOLD_BREACH',
  INVALID_QUANTITY: 'INVALID_QUANTITY',

  RETENTION_OVERRIDE_REQUIRES_LEVEL_5: 'RETENTION_OVERRIDE_REQUIRES_LEVEL_5',
  RETENTION_OVERRIDE_REQUIRES_CD: 'RETENTION_OVERRIDE_REQUIRES_CD',
  RETENTION_PCT_NOT_ALLOWED: 'RETENTION_PCT_NOT_ALLOWED',

  CONCURRENT_MODIFICATION: 'CONCURRENT_MODIFICATION',

  INVALID_TRANSFER_STATE: 'INVALID_TRANSFER_STATE',
  UNKNOWN_DISTRICT: 'UNKNOWN_DISTRICT',
  UNKNOWN_RESOURCE: 'UNKNOWN_RESOURCE',
} as const;

export type ViolationCode = (typeof ViolationCode)[keyof typeof ViolationCode];

export const VIOLATION_HTTP_STATUS: Record<ViolationCode, number> = {
  ROLE_NOT_PERMITTED_AT_LEVEL: 403,
  OUT_OF_SCOPE_QUARTER: 403,
  QC_WITHOUT_QUARTER: 403,

  NO_RESERVATION_AT_LEVEL_1: 403,
  INTER_QUARTER_TRANSFER_FORBIDDEN: 403,
  TRANSIT_FORBIDDEN_AT_LEVEL: 403,

  SAME_SOURCE_AND_DESTINATION: 400,
  NOT_ADJACENT: 422,
  NO_ROUTE_AVAILABLE: 422,
  MARITIME_ROUTE_UNAVAILABLE: 422,
  TRANSIT_APPROVAL_REQUIRED: 409,
  TRANSIT_APPROVAL_DENIED: 409,

  ADJACENT_SOURCE_AVAILABLE: 422,

  INSUFFICIENT_STOCK: 422,
  RETENTION_THRESHOLD_BREACH: 422,
  INVALID_QUANTITY: 400,

  RETENTION_OVERRIDE_REQUIRES_LEVEL_5: 403,
  RETENTION_OVERRIDE_REQUIRES_CD: 403,
  RETENTION_PCT_NOT_ALLOWED: 422,

  CONCURRENT_MODIFICATION: 409,

  INVALID_TRANSFER_STATE: 409,
  UNKNOWN_DISTRICT: 404,
  UNKNOWN_RESOURCE: 404,
};

export interface RuleViolation {
  code: ViolationCode;
  httpStatus: number;
  message: string;
  details?: Record<string, unknown>;
}

export function violation(
  code: ViolationCode,
  message: string,
  details?: Record<string, unknown>,
): RuleViolation {
  return { code, httpStatus: VIOLATION_HTTP_STATUS[code], message, details };
}

// The engine returns, it never throws. The HTTP layer decides what to do.
export type RuleResult<T> =
  | { ok: true; value: T }
  | { ok: false; violation: RuleViolation };

export const ok = <T>(value: T): RuleResult<T> => ({ ok: true, value });
export const fail = <T = never>(v: RuleViolation): RuleResult<T> => ({
  ok: false,
  violation: v,
});
